sudo: false

language: cpp

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

script:
  - make & make test & make coverage


after_success:
  - coveralls --gcov-options '\-lp'